#!/usr/bin/env node
"use strict";

const fs = require("fs")
const langs = require("../json/langs.json")

langs.forEach(lang => {
    console.log(`Building location file for ${lang.name} (${lang.id})...`)
    const id = lang.id
    const oldData = {
        ui: require(`../json/${id}/ui-${id}.json`),
        results: require(`../json/${id}/results-${id}.json`),
        buttons: require(`../json/${id}/buttons-${id}.json`),
        questions: require(`../json/${id}/questions-${id}.json`)
    }
    const newData = {
        lang_name: lang.name,
        translators: lang.authors
    }
    Object.entries(oldData.ui).forEach(([page, content])=> {
        Object.entries(content).forEach(([key, text])=> {
            newData[`ui_${page}_${key}`] = text
        })
    })
    Object.entries(oldData.questions).forEach(([qst, content])=> {
      newData[`question_${qst}`] = content.question
    })
    Object.entries(oldData.results).forEach(([ideo, content])=> {
      newData[`ideo_${ideo}`] = content.result
      newData[`ideo_${ideo}_desc`] = content.desc
    })
    Object.entries(oldData.buttons).forEach(([btn, content])=> {
      newData[`btn_${btn}`] = content.text
    })
    fs.writeFileSync(`./scripts/l10n/${id}.json`, JSON.stringify(newData, null, '  '))
})


console.log(`Building questions file...`)
const questions = []
function addQstData(data) {
    return JSON.stringify(data, null, '    ').split('\n').join('\n        ')
}
Object.entries(require(`../json/en/questions-en.json`)).forEach(([qst, content])=> {
    questions.push(`${qst.match(/^[0-9]/) ? `"${qst}"` : qst}: {
        question: i18n.question_${qst},
        answers: ${addQstData(content.answers)},
        results: ${addQstData(content.results)},
        nextquestion: ${addQstData(content.nextquestion)}
    }`)
})
fs.writeFileSync(
    `./scripts/questions.js`,
    'export default {\n    ' + questions.join(',\n    ') + '\n}'
)


console.log(`Building buttons file...`)
const buttons = []
Object.entries(require(`../json/en/buttons-en.json`)).forEach(([btn, content])=> {
    buttons.push(`${btn}: {
        text: i18n.btn_${btn},
        bgcolor: "${content.bgcolor}",
        textcolor: "${content.textcolor}"
    }`)
})
fs.writeFileSync(
    `./scripts/buttons.js`,
    'export default {\n    ' + buttons.join(',\n    ') + '\n}'
)
